# 默认端口改为80
server:
  port: 80
  servlet:
    context-path: /crm
# 添加静态资源映射
spring:
  mvc:
    format:
      # 让从前台过来的以下日期格式可以被转换（注意，但也只能识别以下格式了）
      date: yyyy-MM-dd
    static-path-pattern: /**
  resources:
    static-locations:
      - classpath:/templates/
      # 通过file://协议引用自定义配置的内容
      - file:///${upload-info.basePath}
  # 整合mybatis-1（设置DB数据源）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Roomysqld-1028
    url: jdbc:mysql://localhost:3306/person_hr?serverTimezone=Asia/Tokyo
    druid:
      initial-size: 5
      max-active: 10
  servlet:
    multipart:
      # 请求参数的最大size（包括文件和诸多普通的参数）
      max-request-size: 15MB
      # 请求文件的最大size
      max-file-size: 10MB
# 整合mybatis-2（设置别名、mapper等）
mybatis:
  # 设置别名
  type-aliases-package: com.lding.domain
  # 设置驼峰转换
  configuration:
    map-underscore-to-camel-case: true
# 配置分页
pagehelper:
  # 数据库方言 mysql
  helper-dialect: mysql
  # 分页参数合理化（默认是false）
  # pageNum <= 0就会自动获取第1页，pageNum >= pages 就会自动获取最后一页
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数（默认是false）
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法;增加了该参数来配置参数映射;
  # 用于从对象中根据属性名取值
  #  默认值为 countSql
  params: countSql
# 自定义文件上传相关配置
upload-info:
  basePath: /opt/
  imagePath: upload/image/